site_name: Iapetus

theme:
  name: material

  palette:
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - mkdocstrings
  - bibtex:
      bib_file: "bibref/iapetus.bib"
      csl_file: "bibref/ieee.csl"
      cite_inline: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/bundle.af94fead.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/timeago.js/2.0.2/timeago.min.js
  - javascripts/timeago_mkdocs_material.js
  - javascripts/custom.0fa778a4.min.js
  - javascripts/bundle.bec7f21d.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.2af97fc9.min.css


nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - Explanation: 
    - Single Target Bayes Filter: explanation/single_target_bayes_filter.md
    - Probability Hypothesis Density: explanation/phd_filter.md
    - State Transition Matrix: explanation/stm.md

