site_name: Iapetus

theme:
  name: material

  palette:
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - mkdocstrings
  - caption
  - bibtex:
      bib_file: "bibref/iapetus.bib"
      csl_file: "bibref/ieee.csl"
      cite_inline: false
      full_bib_command: \full_bibliography


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  

extra_javascript:
  - javascripts/bundle.af94fead.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/timeago.js/2.0.2/timeago.min.js
  - javascripts/timeago_mkdocs_material.js
  - javascripts/custom.0fa778a4.min.js
  - javascripts/bundle.bec7f21d.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.2af97fc9.min.css
  - stylesheets/mermaid.css


nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - definitions.md
  - reference.md
  - Explanation: 
    - explanation/explanation.md
    - Dynamics:
      - Linear Dynamic Systems: explanation/dynamics/linear/top_linear_dynamic_systems.md
      - Nonlinear Dynamic Systems:
        - Astrodynamics:
          - Two Body: explanation/dynamics/nonlinear/astrodynamics/two_body.md
          - Atmospheric Drag: explanation/dynamics/nonlinear/astrodynamics/atmospheric_drag.md
    - Single Target Estimation:
      # - Batch:
      - Sequential:
        - Discrecte Kalman Filter: explanation/single_target_estimation/sequential/dkf.md
        - Linearized Kalman Filter: explanation/single_target_estimation/sequential/lkf.md
        - Extended Kalman Filter: explanation/single_target_estimation/sequential/ekf.md
      - Single Target Bayes Filter: explanation/single_target_estimation/single_target_bayes_filter.md
      - Smoothing: explanation/single_target_estimation/smoothing.md
    - Multiple Target Estimation:
      - Probability Hypothesis Density: explanation/multi_target_estimation/phd_filter.md

