site_name: Iapetus

theme:
  name: "material"
  features:
    # - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - mkdocstrings
  - bibtex:
      bib_file: "bibref/iapetus.bib"
      csl_file: "bibref/ieee.csl"
      cite_inline: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

extra_javascript:
  # - javascripts/mathjax.js   # Removing this line for 404 warn. Removal doesn't seem to be an issue.
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - Explanation: 
    - Single Target Bayes Filter: explanation/single_target_bayes_filter.md
    - Probability Hypothesis Density: explanation/phd_filter.md
    - State Transition Matrix: explanation/stm.md

