site_name: Iapetus

theme:
  name: "material"
  features:
    # - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - Explanation: 
    - Single Target Bayes Filter: explanation/single_target_bayes_filter.md
    - Probability Hypothesis Density: explanation/phd_filter.md
    - State Transition Matrix: explanation/stm.md
